import numpy as np 
a = np.full((4,4), 0)
b = np.array((np.arange(1,10).reshape(3,3)))
#print("this is a: \n", a)
#print("this is b: \n", b)
c = np.full_like(b, 5)
c = np.full(b.shape, 8)
#print (c)
d = np.random.rand(3,3)
e = np.random.randint(0,10,(3,3))
f = np.identity(4).astype('int64')
#print (f)
#print (np.cos(b))
g = np.vstack((b,c))
h = np.hstack((b,c))
i = ~(b >= 3) & (b < 8)
j = b[b>5]
k = b.reshape(1,9)
#print (k[0,[2,3,7]])
l = np.array([1,2,3,4,5,6,7,8,9])
#print(l[[2,3,7]])
print (b)
print (i)
